### ISSUE TITLE
Add schema support

### ISSUE THREAD

**Issue by lawrencecchen** [RobinBlomberg/kysely-codegen#10]
I have schemas other than public.

**Comment by koskimas** [comment]
How do you use your schemas? I mean there are at least two ways to use them, both of which should lead to different generated types. Please see [this](https://github.com/koskimas/kysely/blob/master/recipes/schemas.md) document and tell us which one (1 or 2) you mean.

As a side note, you'll be more likely to get answers and help if your issues sounded more like requests than demands 🙂

**Comment by lawrencecchen** [comment]
I'm using the first case in which the schemas are enumerable. eg. I have a public schema and a stripe schema.

Sorry if I came off as demanding. I love this project (and kysely!), and would love to contribute.

**Comment by koskimas** [comment]
Looking at the code, you should get the tables in the types, but currently without the schema prefix. Is this the case?

**Comment by koskimas** [comment]
I created a PR that adds basic support for "enumeraable" postgres schemas.
