### ISSUE TITLE
0.10.1 tag?

### ISSUE THREAD

**Issue by arusahni** [RobinBlomberg/kysely-codegen#100]
Thanks for the wonderful package. I see that 0.10.1 is the latest version, but do not see a corresponding tag in this repo. Would it be possible to push one? It's helpful to see what's changed between versions.

**Comment by RobinBlomberg** [comment]
`kysely-codegen@0.11.0` has been released! It has a tag and a changelog—hope you like it!

**Comment by arusahni** [comment]
Thank you!
