### ISSUE TITLE
Schema Names Starting with Number Generate Invalid TypeScript

### ISSUE THREAD

**Issue by billdybas** [RobinBlomberg/kysely-codegen#102]
Hi there! Thank you for creating this project. 🙏 

I'm using Postgres & noticed this behavior on schemas that contain a number.

```sql
CREATE SCHEMA "1";

CREATE TABLE "1".example (
  id SERIAL PRIMARY KEY
);
```

Generates the following:
```ts
import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface 1Example {
  id: Generated<number>;
}

export interface DB {
  "1.example": 1Example;
}
```

And there are TypeScript errors on the `1Example` interface: 
- `Interface name cannot be '1'. ts(2427)`
- `An identifier or keyword cannot immediately follow a numeric literal. ts(1351)`

I wonder if you could identify if the schema name contains a number character and convert it to a word representation instead?

For example:
```ts
import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface OneExample {
  id: Generated<number>;
}

export interface DB {
  "1.example": OneExample;
}
```

**Comment by RobinBlomberg** [comment]
Hello! I believe this should be fixed in `kysely-codegen@0.11.0`—please check it out!
