### ISSUE TITLE
eslint config impacting my project?

### ISSUE THREAD

**Issue by sbauch** [RobinBlomberg/kysely-codegen#103]
I'm having a bunch of issues with my eslint when I have this project as a `devDependency`?

vscode eslint ouput shows:

```
Error: Failed to load config "@robinblomberg/robinblomberg" to extend from.
Referenced from: /Users/samuelsbauch/Code/annotax/packages/app/node_modules/kysely-codegen/package.json
    at configInvalidError (/Users/samuelsbauch/Code/annotax/packages/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2639:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/samuelsbauch/Code/annotax/packages/app/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3270:23)
```

I've never seen anything like this so im not sure how to tell eslint to not inherit your config? Would it be possible to remove your eslint config from the package? Or is there another solution I can use?

Maybe I shouldn't have this as a dependency and instead install globally? Really frustrating, it makes my autofix on save take 5+ seconds, just killing my devex.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/103">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/103/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/103/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
Hello! I'm not sure what has been causing this for you, and I'm not even sure it's something within our control. Please check your ESLint config and your VS Code settings (if you're using VS Code) to make sure it's not inadvertently reading the config from `node_modules`. Also make sure to check out the new 0.11.0 version, just in case it solves anything.

**Comment by RobinBlomberg** [comment]
I will reopen this if it proves to still be a problem.
