### ISSUE TITLE
Support for MSSQL

### ISSUE THREAD

**Issue by panuchka** [RobinBlomberg/kysely-codegen#104]
Hi, since Kysely now (almost) officially has an [MSSQL support,](https://github.com/kysely-org/kysely/tree/master/src/dialect/mssql) would it be possible to add support for it in the codegen? 🙏 Or is this a big task?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/104">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/104/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/104/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
Hello!

While it looks like MSSQL is being worked on in the Kysely repo, it doesn't seem like it's part of any release yet, so I cannot add support for it yet. It will probably be quite straightforward when it's ready though.

**Comment by ericwilhite** [comment]
Resurfacing this since MSSQL is in the latest documented kysely release. 

We have awaited kysely support for MSSQL for quite some time. Would be wonderful to generate types!

**Comment by mjbergman92** [comment]
Unrelated to kysely, there are some issues with TLS encryption protocols with some older versions of MS SQL Server. In my experience, I have not been able to use tedious drivers without disabling encryption.

I'm considering adding a flag --no-encrypt to set the encrypt field to false inside of the connection configuration. Right now, I do not believe there is a work around as the only inputs are the connection string, unless I can get TLS configuration to work properly.
