### ISSUE TITLE
Make domain support optional

### ISSUE THREAD

**Issue by RobinClowers** [RobinBlomberg/kysely-codegen#112]
Hey folks, love this library. I've been using for a while now with [Materialize](materialize.com/), which strives to be postgres compatible. However, we don't support the standard `WITH RECURSIVE` syntax that postgres has, so v0.11 won't run against Materialize.

Would you consider adding (or accepting a patch) to make the domain support added in https://github.com/RobinBlomberg/kysely-codegen/pull/68 optional? Materialize also doesn't support domains, so it would be great it we just turn this feature off.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/112">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/112/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/112/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
I would definitely accept a patch! Good call - didn't know this would break anything.
