### ISSUE TITLE
Generate typescript comments based on columns comments

### ISSUE THREAD

**Issue by maktouch** [RobinBlomberg/kysely-codegen#127]
Most databases support having a `comment` field for each columns. We could extract the comment, and output it to the definition file. 

Example: 

This schema

```sql
CREATE TABLE `customer_metrics` (
  `company_id` bigint unsigned NOT NULL,
  `date` date NOT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `customer_email` text,
  `remote_customer_id` varchar(255) NOT NULL,
  `mrr` decimal(16,4) DEFAULT NULL COMMENT 'Monthly Recurring Revenue in USD',
  `ltv` decimal(16,4) DEFAULT NULL COMMENT 'Lifetime Value in USD',
  PRIMARY KEY (`company_id`,`date`),
  KEY `customer_metrics_date` (`date`),
  KEY `customer_metrics_company_id` (`company_id`),
  KEY `customer_metrics_remote_customer_id` (`remote_customer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

would output this: 

```typescript
export interface CustomerMetrics {
  company_id: number
  customer_email: string | null
  date: Date
  /**
   * Lifetime Value in USD
   */
  ltv: Decimal | null
  /**
   * Monthly Recuring Revenue in USD
   */
  mrr: Decimal | null
  remote_customer_id: string
  updated_at: Generated<Date>
}
```

which would enable this: 

<img width="392" alt="image" src="https://github.com/RobinBlomberg/kysely-codegen/assets/1134251/821528a5-4de3-4254-becf-ace6d95286f7">

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/127">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/127/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/127/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
This is a great idea! This should definitely be added.
