### ISSUE TITLE
v0.12.0 not marked as latest in npm

### ISSUE THREAD

**Issue by BoscoDomingo** [RobinBlomberg/kysely-codegen#132]
![image](https://github.com/RobinBlomberg/kysely-codegen/assets/46006784/c0c69291-41bb-42c4-9e62-d14fdd9a2147)

https://www.npmjs.com/package/kysely-codegen?activeTab=versions

This causes multiple managers to error

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/132">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/132/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/132/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
Upgraded to `0.13.0` now!

If memory serves me right, there was some bug in some dependency that led me to not mark it as the latest version.
