### ISSUE TITLE
0.13 breaking changes

### ISSUE THREAD

**Issue by michael-land** [RobinBlomberg/kysely-codegen#135]
Upgrading from version 0.11 to 0.13 results in an error related to the PostgreSQL array type. Generated array type changed from `T[]` to `ArrayType<T>`

code
```ts
export type ArrayType<T> = T extends ColumnType<infer S, infer I, infer U> ? ColumnType<S[], I[], U[]> : T[];

type X = 'A' | 'B';
type Xs = X[];

type Table = {
  xs: ArrayType<X>;
};

const input: Insertable<Table> = {
  xs: ['A', 'B'],
};
```

screenshots
![CleanShot 2024-03-07 at 23 49 59@2x](https://github.com/RobinBlomberg/kysely-codegen/assets/33362998/dc78e045-a51d-4f31-8bcc-ceb7ca0ea94d)
![CleanShot 2024-03-07 at 23 50 08@2x](https://github.com/RobinBlomberg/kysely-codegen/assets/33362998/54cd48c0-9cc3-4aef-8b37-b4b7675df74e)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/135">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/135/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/135/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
Thanks for reporting! I'll jump on this immediately.

**Comment by RobinBlomberg** [comment]
This feels like a TypeScript limitation, because I'm not sure why these behave differently...

![image](https://github.com/RobinBlomberg/kysely-codegen/assets/20827397/2f8a3657-5d89-4aea-b69d-959a7a721d09)

Anyway, I'll find a solution. Be back soon.

**Comment by RobinBlomberg** [comment]
Not the most beautiful thing, but it works! Expect a new version within ~15 minutes.

![Arrayz](https://github.com/RobinBlomberg/kysely-codegen/assets/20827397/1e05a37e-c396-4632-88f2-e3ea8e68fa4d)

**Comment by RobinBlomberg** [comment]
Released!
