### ISSUE TITLE
Outdated v0.5 dist build on npm

### ISSUE THREAD

**Issue by miles-crighton** [RobinBlomberg/kysely-codegen#14]
Hey, super excited to start using this tool, thanks for building it!

I was just looking into using the new `--camel-case` flag that came in the latest release **v0.5**, however it looks like it's missing from the compiled _dist_ code [published on npm](https://www.npmjs.com/package/kysely-codegen) (can be found under the _Explore_ tab), where as the changes (such as the _case_converter.ts_ file) are available and published in _src_. Possibly a mistake during publishing?

**Comment by RobinBlomberg** [comment]
It was a mistake! I added a script that builds on publish now, so this shouldn't happen again.

Fixed in `kysely-codegen@0.5.1` - thanks!
