### ISSUE TITLE
How to specify different .env variable for DATABASE_URL

### ISSUE THREAD

**Issue by srapport** [RobinBlomberg/kysely-codegen#143]
We have multiple databases in the same project that have different connection strings. Is there a way to specify the `.env` variable to use in the `kysely-codegen` command line?

For example:

`kysely-codegen --env-var CORE_PRODUCT_DB_URL ...`
`kysely-codegen --env-var LICENSING_DB_URL ...`

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/143">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/143/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/143/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
Hey!

You can use `kysely-codegen --url=env(CORE_PRODUCT_DB_URL)`. 😊

If you need to specify the environment file, you can use `--env-file` as well.

Hope that helps!

**Comment by srapport** [comment]
Hi @RobinBlomberg,

I wanted to circle back on this as `--url=env(VAR_NAME)` never worked and I see a related open issue #168. This is a really important feature of the command line inputs.

**WORKAROUND:** The only workaround I could find _(and currently use)_ has been a whole stack of `.env.database_name` files containing a single `DATABASE_URL`, then a stack of package scripts for each passing `--env-file .env.database_name`.

As projects grow, anybody touching a project must have a whole stack of env files.

Is this a bug, bad docs, or pilot error not knowing the right syntax?

Thank you.

**Comment by thobhanifreddy** [comment]
I’m facing the same issue. I’ve opened a [discussion](https://github.com/RobinBlomberg/kysely-codegen/discussions/246) to explore this further with a possible solution.
