### ISSUE TITLE
`--print` command line argument doesn't work

### ISSUE THREAD

**Issue by glacius-mitchell** [RobinBlomberg/kysely-codegen#144]
## Problem description

Invoking the CLI with `--print` doesn't actually print the generated output file to the terminal.

## Identified cause

I believe the issue is that `Cli.generate` is not propagating `options.print` to the underlying `await generator.generate({ ... })` call, meaning the generator is always receiving `print: undefined` regardless of what was specified on the command line:

https://github.com/RobinBlomberg/kysely-codegen/blob/be70e2556d9e80313b693288f9328a113458e290/src/cli/cli.ts#L82-L94

## Proposed fix

Assuming that's the case, the fix should be as simple as adding `print: options.print` to the function call above.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/144">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/144/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/144/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
Thanks for reporting! I fixed it now in `0.14.2`!
