### ISSUE TITLE
--runtime-enums not working as expected

### ISSUE THREAD

**Issue by avermeil** [RobinBlomberg/kysely-codegen#152]
Hello!

I believe that there is an issue with the `--runtime-enums` flag.

Given this mysql table definition:

```sql
CREATE TABLE `campaign_attributes` (
  `opt_account_id` varchar(30) NOT NULL,
  `id` bigint unsigned NOT NULL,
  `name` varchar(250) DEFAULT NULL,
  `status` enum('ENABLED','PAUSED','REMOVED','ENABLED_NOT_SERVING','UNKNOWN') NOT NULL,
  PRIMARY KEY (`opt_account_id`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
/*!50100 PARTITION BY KEY (opt_account_id)
PARTITIONS 100 */;
```

And this command:

```
kysely-codegen --runtime-enums --camel-case --dialect mysql --url 'mysql://db/warehouse?user=user&password=password'
```

I get the output:

```typescript
export interface CampaignAttributes {
  id: number;
  name: string | null;
  optAccountId: string;
  status: "ENABLED" | "ENABLED_NOT_SERVING" | "PAUSED" | "REMOVED" | "UNKNOWN";
}
```

This is with `kysely-codegen@0.15.0`.

Shouldn't the output be using enums instead of strings for the field `status`?

Thanks for any help :)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/152">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/152/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/152/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
Hello! `--runtime-enums` only applies to PostgreSQL enums, which are named data types that exist outside of the tables. We could in theory extract MySQL enums as separate types as well, but it wouldn't model the database as accurately, and it's not obvious how they should be named (`CampaignAttributesStatus` or `CampaignAttributeStatus`?) or how they should work (should the enum be reused if another column has the same values?).

I will update the `--help` text to show that the option only applies to PostgreSQL enums.

If you really want this feature, feel free to create a new issue!

**Comment by avermeil** [comment]
@RobinBlomberg Fair enough, thanks for the update!
