### ISSUE TITLE
kysely-bun-worker vs kysely-bun-sqlite

### ISSUE THREAD

**Issue by angelxmoreno** [RobinBlomberg/kysely-codegen#153]
[kysely-bun-worker](https://github.com/subframe7536/kysely-sqlite-tools/tree/master/packages/dialect-bun-worker) and [kysely-bun-sqlite](https://github.com/dylanblokhuis/kysely-bun-sqlite) are two different dialects that work with `bun:sqlite`. However, internally the naming used for the kysely-bun-worker dialect is called `bun-sqlite`. At first glance the name implies that `kysely-bun-sqlite` is what is used internally. It took me sometime to figure out why my setup wasn't working because of this confusion. 

In my app I am using `kysely-bun-sqlite` and I am unable to use codegen. I'd like to propose we rename the current dialect from `bun-sqlite` to `bun-sqlite-worker` and include the `kysely-bun-sqlite` dialect to avoid future confusion.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/153">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/153/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/153/pledge.svg">
</picture>
</a>

**Comment by njoshi22** [comment]
Actually just saw the same thing with postgres too - the schema files in both were different (one was updated, one was not).

**Comment by tlonny** [comment]
I've tried to address this here: https://github.com/RobinBlomberg/kysely-codegen/pull/174

N.B.

I opted for: `kysely-bun-sqlite` and `worker-bun-sqlite`

Instead of: `kysely-bun-sqlite` and `bun-sqlite-worker`

As I feel the former is more consistently named. Please let me know your thoughts...

**Comment by angelxmoreno** [comment]
@tlonny agreed

**Comment by RobinBlomberg** [comment]
Should be released in [kysely-codegen@0.16.0](https://github.com/RobinBlomberg/kysely-codegen/releases/tag/0.16.0)! 🚀
