### ISSUE TITLE
Postgresql generated types

### ISSUE THREAD

**Issue by tzezar** [RobinBlomberg/kysely-codegen#171]
Some columns are mapped properly to `string` and some are randomly mapped to `Generated<string>` 

```
export interface JednostkaMiary {
  id: Generated<number>;
  nazwa: string;
  skrot: string;
}

export interface KategoriaAsortymentu {
  id: Generated<number>;
  nazwa: Generated<string>;
  opis: Generated<string>;
}
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/171">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/171/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/171/pledge.svg">
</picture>
</a>

**Comment by bakasmarius** [comment]
It is not random, that is most probably because all `Generated` columns have a `default` value in your database schema.

**Comment by tzezar** [comment]
> It is not random, that is most probably because all `Generated` columns have a `default` value in your database schema.

You are right
