### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by pbrink231** [RobinBlomberg/kysely-codegen#178]
Been trying to get this going for a little bit.  From my experience I think it would be beneficial to add some information to the readme.

- Add example using --out-file
`npx kysely-codegen --out-file ./src/db/db.d.ts`

- Show how to use this compared to the getting started documentation on kysely
In the [https://kysely.dev/docs/getting-started](startup documentation) you can write your own schema and you create Person, NewPerson, PersonUpdate.  these are used later in the app.
Showing an example that now you use the generated person using the helper types: Selectable<Person>, Insertable<Person> or Updatable<Person>.  Otherwise you get an error yelling about ColumnType missmatch.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/178">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/178/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/178/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
Implemented now in [kysely-codegen@0.17.0](https://www.npmjs.com/package/kysely-codegen)!
