### ISSUE TITLE
Usage in CI pipeline?

### ISSUE THREAD

**Issue by ClayenKitten** [RobinBlomberg/kysely-codegen#179]
What is the preferred way to do CI with kysely-codegen? Currently checking types gives errors like that:

```
Error: Argument of type 'string' is not assignable to parameter of type 'ReferenceExpression<DB, never>'. 
			.updateTable("user")
			.where("id", "=", user.id)
			.set({ passwordHash })
```

I could probably start docker compose with Postgres during CI, run migrations and generate types. However, that seems like an overkill. Is there a simpler option that I am missing?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/179">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/179/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/179/pledge.svg">
</picture>
</a>

**Comment by brianmcd** [comment]
Is the issue that you don't have the generated types available on your CI server? If so, you can just check the generated types into your repo. You can configure where the types are written with `--out-file` to make that easier.

**Comment by ClayenKitten** [comment]
Oh, I didn't know about that option. Thanks!
