### ISSUE TITLE
How to specify output path for generated types?

### ISSUE THREAD

**Issue by biryusal** [RobinBlomberg/kysely-codegen#180]
I got it, — by default generated types are stored in `/node_modules/kysely-codegen/dist/db.d.ts`, but I want to specify output path to `src/types/database/db.d.ts`, — how do I do that? I didn't find anything similar with this in documentation

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/180">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/180/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/180/pledge.svg">
</picture>
</a>

**Comment by brianmcd** [comment]
`kysely-codegen --out-file=src/types/database/db.d.ts`

**Comment by lintellme99** [comment]
Thank you so much!

**Comment by RobinBlomberg** [comment]
Glad you solved it! I'll close this issue.
