### ISSUE TITLE
How to generate `enum` as `enum`?

### ISSUE THREAD

**Issue by lintellme99** [RobinBlomberg/kysely-codegen#182]
All my `enum`s in `PostgreSQL` are generated into `type`

For example, `PostgreSQL`:
```
CREATE TYPE "app_status" AS ENUM (
  'running',
  'not_started',
  'down'
);
```

Becomes:
```
export type AppStatuses =
  | 'running'
  | 'not_started'
  | 'down'
```
After `codegen`

Is it possible to generate `enum` as `enum`?
For example:
```
export enum AppStatuses {
  RUNNING = 'running',
  NOT_STARTED = 'not_started',
  DOWN = 'down'
} 
```
I want to use it as a:
```
if (app_status === AppStatuses.DOWN) {
  ...
}
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/182">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/182/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/182/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
Hello! You can use the `--runtime-enums` to generate them. ✨

**Comment by lintellme99** [comment]
Thank you so much!
I've dig a little deeper and found the solution, but you were literally faster

Thank you so much!
