### ISSUE TITLE
CliOptions.schemas should be optional.

### ISSUE THREAD

**Issue by onehorsetown** [RobinBlomberg/kysely-codegen#193]
I see you added the following to CliOptions:

```
export type CliOptions = {
...
    schemas: string[];
}
```

Seems like it should be optional as it is in `GenerateOptions`:

https://github.com/RobinBlomberg/kysely-codegen/blob/e444c151b22c2e2c4185109d39a8848843a86aac/src/generator/generator/generate.ts#L27

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/193">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/193/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/193/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
Should be fixed now in [kysely-codegen@0.17.0](https://www.npmjs.com/package/kysely-codegen)!
