### ISSUE TITLE
Version 0.16.4 doesn't export DB from index.js

### ISSUE THREAD

**Issue by daviduzumeri** [RobinBlomberg/kysely-codegen#195]
The documentation still says to import `DB` from `kysely-codegen`, but you need to import it from `kysely-codegen/dist/db` with 0.16.4. I think it's a missing export still? I know the index was missing in a previous issue (https://github.com/RobinBlomberg/kysely-codegen/issues/191) but for those of us who still codegen to inside the node_modules boundary it's an undocumented breaking change (and also importing from `dist` just always sets off aesthetic klaxons for me :)).

Thanks a ton for the package btw, it's been a lifesaver for us!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/195">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/195/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/195/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
I forget that `DB` is imported in this way. I will fix! Thanks.

**Comment by RobinBlomberg** [comment]
Fixed in `kysely-codegen@0.16.5`.
