### ISSUE TITLE
Postgres: if you set the flag `partitions`, it's not taken into account

### ISSUE THREAD

**Issue by fxmouthuy** [RobinBlomberg/kysely-codegen#196]
After the new `0.16.+` and the introduction of the partitions filtering for Postgres, the cli option `partitions` is actually not working.

It's also filtering out all inherited tables and not just partitions. 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/196">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/196/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/196/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
Fixed in `kysely-codegen@0.16.6`.
