### ISSUE TITLE
Custom dialect?

### ISSUE THREAD

**Issue by ctrlplusb** [RobinBlomberg/kysely-codegen#20]
Is it possible to provide a custom dialect? I want to use the new Planetscale one.

**Comment by ctrlplusb** [comment]
Ah, think it's fine to just use the mysql one as the generation doesn't depend on foreign keys (which Planetscale's mysql doesn't support).

Closing. ♥️

**Comment by Azarattum** [comment]
What about the SurrealDB one? Or any custom dialects in general? Is there some kind of plugin system in-place to write your own adapter like the one Kysely itself has?

**Comment by RobinBlomberg** [comment]
There is not (yet). Feel free to create an issue!
