### ISSUE TITLE
Incorrect postgres Timestamp column type

### ISSUE THREAD

**Issue by aheckmann** [RobinBlomberg/kysely-codegen#201]
[This commit](https://github.com/RobinBlomberg/kysely-codegen/commit/98c974b3fc97273fbe2c0170706bc52d7945430b) broke Postgres `Timestamp` types. When selecting timestamp columns, the `pg` driver returns `Date` objects, not strings. As such, now our codebase is filled with incorrect ts errors about the return value possibly being a string. 

Update: It appears the bug began in 0.16.4. 0.16.0 and 0.15.0 are working correctly with `export type Timestamp = ColumnType<Date, Date | string, Date | string>;`

<img width="464" alt="image" src="https://github.com/user-attachments/assets/b9703373-577f-4238-93c0-ccda47ec55c2">

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/201">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/201/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/201/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
Hey, thanks for reporting! I have now reverted this change in `kysely-codegen@0.16.8`. Thanks!
