### ISSUE TITLE
Deduplicated `ColumnType` type arguments are incorrect

### ISSUE THREAD

**Issue by glacius-mitchell** [RobinBlomberg/kysely-codegen#203]
I believe the `ColumnType` type argument deduplication logic in https://github.com/RobinBlomberg/kysely-codegen/commit/ad03d2ef67f40c7d22df27e30a16bcf6083da463 was incorrect.

In particular, it assumed an omitted update type would default to the insert type, when in fact Kysely's update type defaults to the select type (see https://github.com/kysely-org/kysely/blob/0.27.4/src/util/column-type.ts#L41).

This led to some regressions in the types generated by `kysely-codegen`.

For instance, where we previously had these generated types

```typescript
export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;
```

which expanded to

```typescript
type Int8 = {
    readonly __select__: string;
    readonly __insert__: string | number | bigint;
    readonly __update__: string | number | bigint;
}

type Timestamp = {
    readonly __select__: Date;
    readonly __insert__: string | Date;
    readonly __update__: string | Date;
}
```

we now have these generated types

```typescript
export type Int8 = ColumnType<string, bigint | number | string>;

export type Timestamp = ColumnType<Date, Date | string>;
```

which expand to

```typescript
type Int8 = {
    readonly __select__: string;
    readonly __insert__: string | number | bigint;
    readonly __update__: string;
}

type Timestamp = {
    readonly __select__: Date;
    readonly __insert__: string | Date;
    readonly __update__: Date;
}
```

The new column types are overly strict on what types of values can be specified for an update.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/203">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/203/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/203/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
Should be fixed now in [kysely-codegen@0.17.0](https://www.npmjs.com/package/kysely-codegen)!
