### ISSUE TITLE
Add support for enums

### ISSUE THREAD

**Issue by thelinuxlich** [RobinBlomberg/kysely-codegen#21]
Currently it generates the enum field with the unknown type

**Comment by RobinBlomberg** [comment]
Thank you for the issue!

I will investigate how difficult this would be to add. It will probably require writing new introspection logic for MySQL/PostgreSQL for either kysely or kysely-codegen.

**Comment by koskimas** [comment]
Enums are different on all dialects. Sqlite doesn't have them, mysql has the `enum('a', 'b', 'c')` data type and on postgres you need to create a new type using `CREATE TYPE my_enum AS ENUM ('a', 'b', 'c')` (or something like that). In addition to using the enum type, many people opt to use a `CHECK` constraint instead on postgres. Parsing that in a reliable way is impossible. For example knex creates a check constraint on postgres if you don't specifically instruct it to create an enum type.

On postgres it's possible to get the values of an enum type, but I'm not sure about mysql.

**Comment by 0xDing** [comment]
> 谢谢你的问题！
> 
> 我将调查添加这将是多么困难。它可能需要为 kysely 或 kysely-codegen 为 MySQL/PostgreSQL 编写新的自省逻辑。

https://github.com/kristiandupont/kanel  FYI

**Comment by thelinuxlich** [comment]
Interesting project!

**Comment by RobinBlomberg** [comment]
Interesting indeed.

Relevant PostgreSQL query:

https://github.com/kristiandupont/extract-pg-schema/blob/master/src/kinds/extractEnum.ts

```
SELECT
  json_agg(pg_enum.enumlabel ORDER BY pg_enum.enumsortorder) as "values"
FROM
  pg_type
  JOIN pg_namespace ON pg_type.typnamespace = pg_namespace.oid
  JOIN pg_enum ON pg_type.oid = pg_enum.enumtypid
WHERE
  pg_type.typtype = 'e'
  AND pg_namespace.nspname = :schema_name
  AND typname = :type_name
```

I can verify that it works for getting the values of a specific enum type.

It should probably not be too hard to find a similar query for MySQL, and then we're basically there.

**Comment by RobinBlomberg** [comment]
Nevermind - even better, to list all enums and all their possible values in PostgreSQL:

```sql
SELECT
  pg_type.typname AS enum_type,
  pg_enum.enumlabel AS enum_label
FROM pg_type
JOIN pg_enum
ON pg_enum.enumtypid = pg_type.oid;
```

**Comment by RobinBlomberg** [comment]
For MySQL (will need some extra queries and string parsing):

```sql
SELECT(COLUMN_TYPE, 5)
FROM information_schema.COLUMNS
WHERE TABLE_SCHEMA='foo' 
AND TABLE_NAME='bar'
AND COLUMN_NAME='baz';
-- ('abc','xyz')
```

**Comment by RobinBlomberg** [comment]
I'll have to test this some more, but it works (v0.7.0)!

PostgreSQL:

![EnumPg](https://user-images.githubusercontent.com/20827397/190135155-dcc6b842-a031-4e3b-bcae-2f2d1b56e608.png)

MySQL:

![EnumMysql](https://user-images.githubusercontent.com/20827397/190135176-a30132d7-eb14-4718-a6b6-7098e14c85b8.png)

**Comment by koskimas** [comment]
> Nevermind - even better, to list all enums and all their possible values in PostgreSQL:
> 
> ```sql
> SELECT
>   pg_type.typname AS enum_type,
>   pg_enum.enumlabel AS enum_label
> FROM pg_type
> JOIN pg_enum
> ON pg_enum.enumtypid = pg_type.oid;
> ```

Remember to handle schemas correctly with these. I think this will return all enums of all schemas. You might have the same enum with different values in different schemas.

**Comment by RobinBlomberg** [comment]
Good call! I'll make sure that it handles schemas correctly. 👍

**Comment by RobinBlomberg** [comment]
Added in `kysely-codegen@0.7.0`!

**Comment by Tyflomate** [comment]
Hello, is it possible to see your associated migration file ? When i generate I do not have a enum type created but this:
```typescript
role: 'Admin' | 'Manager' | 'Owner' | 'User' | null;
```
