### ISSUE TITLE
Add schema to the generated types

### ISSUE THREAD

**Issue by gislerro** [RobinBlomberg/kysely-codegen#219]
I have multiple schemas `A` and `B` that both have a table named `foo`. Introspecting the database with `kysely-codegen` generates two interfaces of the same name:
```typescript
export interface Foo {
   id: Generated<string>;
   im_in_a: string
}
export interface Foo {
  id: Generated<string>;
  im_in_b: string
}
export interface DB {
   foo: Foo,
   foo: Foo
}
```

Ideally codegen would respect the schema of the tables [(kysely docs)](https://kysely.dev/docs/recipes/schemas):
```typescript
export interface DB {
  "A.foo": AFoo,
  "B.foo": BFoo
}
```

this functionality is somewhat related to #211 

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/219">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/219/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/219/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
Great that you solved it! The next version will coincidentally rename `--schema` to `--default-schema` for extra clarity. 👍
