### ISSUE TITLE
Wrong type definition for jsonb&json type in postgres

### ISSUE THREAD

**Issue by 0xDing** [RobinBlomberg/kysely-codegen#22]
https://github.com/RobinBlomberg/kysely-codegen/blob/474295a01003f0cc5f2b5f2fb9259e2f6c5f5686/src/dialects/postgres/postgres-adapter.ts#L75

This should be string or object, not number.

**Comment by RobinBlomberg** [comment]
True! That is decidedly a typo. As soon as I have time (probably later today), I'll add something like this:

```typescript
export type Json = JsonArray | JsonObject | JsonPrimitive;

export type JsonArray = Json[];

export type JsonObject = { [K in string]?: Json };

export type JsonPrimitive = boolean | null | number | string;

...

{
  json: new IdentifierNode('Json'),
  jsonb: new IdentifierNode('Json'),
},
```

**Comment by RobinBlomberg** [comment]
Fixed!
