### ISSUE TITLE
Can't use the kysely-bun-sqlite dialect option

### ISSUE THREAD

**Issue by davidmh** [RobinBlomberg/kysely-codegen#220]
Hi there,

I'm using bun and I'm trying to pass the `kysely-bun-sqlite` dialect option but when I run the command, I get: `error: Cannot find package 'better-sqlite3'`.

Here's what I'm doing:

<details>
<summary>package.json</summary>

```json
{
  "scripts": {
    "generate-types": "kysely-codegen --dialect kysely-bun-sqlite --out-file ./api/schema.ts"
  },
  "dependencies": {
    "kysely": "^0.27.4",
    "kysely-bun-sqlite": "^0.3.2",
    "kysely-ctl": "^0.9.0"
  },
  "devDependencies": {
    "@types/bun": "^1.1.14",
    "kysely-codegen": "^0.17.0"
  }
}
```
_edited for brevity_
</details>

<details>
<summary>.config/kysely.config.ts</summary>

```typescript
import { Database } from "bun:sqlite";
import { BunSqliteDialect } from 'kysely-bun-sqlite';
import { defineConfig } from 'kysely-ctl'

const { DATABASE_URL } = process.env;

if (!DATABASE_URL) {
  throw new Error('DATABASE_URL is not set')
}

export const dialect = new BunSqliteDialect({
  database: new Database(DATABASE_URL),
});

export default defineConfig({
  dialect,
  migrations: {
    migrationFolder: "migrations",
  },
  plugins: [],
});
```
</details>

<details>
<summary>command output</summary>

```
❯ bun --bun run generate-types                                                       
$ kysely-codegen --dialect kysely-bun-sqlite --out-file ./api/schema.ts
• Loaded environment variables from '.env'.
• Using dialect 'kysely-bun-sqlite'.
error: Cannot find package 'better-sqlite3' from '[...]/node_modules/kysely-codegen/dist/introspector/dialects/sqlite/sqlite-dialect.js'

Bun v1.1.34 (macOS arm64)
error: script "generate-types" exited with code 1
```
</details>

Am I missing something?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/220">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/220/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/220/pledge.svg">
</picture>
</a>

**Comment by davidmh** [comment]
Looks like I was misinterpreting the purpose of the dialect, I was assuming that using `kysely-bun-sqlite` as a dialect was meant to replace the use of `better-sqlite3`, since the documentation says:

> Driver unsupported
> Kysely's built-in SQLite dialect does not work in Bun because the driver library it uses, "better-sqlite3", doesn't. You have to use a community SQLite dialect that works in Bun, or implement your own.

But adding `better-sqlite3` solves the problem, does the documentation needs to be rephrased?

**Comment by RobinBlomberg** [comment]
Hey, glad you solved it! I guess that's a documentation issue for the [kysely](https://github.com/kysely-org/kysely) project.
