### ISSUE TITLE
MySQL JSON Type

### ISSUE THREAD

**Issue by thdxr** [RobinBlomberg/kysely-codegen#25]
I believe the MySQL JSON type should be something like this
```
export type JSON = ColumnType<{ [key: string]: any }, string, string>
```

This is because it requires you to stringify it on write but it's parsed on read - also wondering if we can give this a more specific type.  Can't use declaration merging right now because you can't merge over a string

**Comment by RobinBlomberg** [comment]
Fixed! It now serializes as:

```ts
export type Json = ColumnType<JsonValue, string, string>;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [K in string]?: JsonValue;
};

export type JsonPrimitive = boolean | null | number | string;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface Test {
  json: Json;
}
```

The point about giving the fields more specific (custom) types has come up before, but I'm not sure how I would approach that. I'd happily welcome a new issue for that!
