### ISSUE TITLE
Loosen the version requirement for kysely peer dependency

### ISSUE THREAD

**Issue by AlexandrLi** [RobinBlomberg/kysely-codegen#29]
Hello. I'm using sst-dev for my project. It was recently updated to use kysely-codegen under the hood to generate types for DB client.
Now we have an issue with peer dependencies.
![image](https://user-images.githubusercontent.com/12869457/190403866-aa236df7-13b9-4f13-b489-5c2090703c54.png)
Is it possible to allow "0.x" kysely version in peer dependencies? Thanks!

**Comment by RobinBlomberg** [comment]
There's the PR #27 that will fix this, so this will be fixed in the next release.

**Comment by AlexandrLi** [comment]
@RobinBlomberg That's great! Do you have any timeframe for the next release?

**Comment by RobinBlomberg** [comment]
Probably no later than Monday. Hopefully sooner!

**Comment by AlexandrLi** [comment]
Issue resolved in 0.6.1. Thanks!
