### ISSUE TITLE
bigserial type generates as string type

### ISSUE THREAD

**Issue by AlexandrLi** [RobinBlomberg/kysely-codegen#31]
Hello. I've noticed some inconcistency in generated type. I have such kind of schema
![image](https://user-images.githubusercontent.com/12869457/192156879-68eba636-e4df-4558-bee3-059f16f5f351.png)
kysely-codegen generates type as
![image](https://user-images.githubusercontent.com/12869457/192156914-12db6c40-c1bf-4330-9dd1-22cc2555397e.png)
![image](https://user-images.githubusercontent.com/12869457/192156929-54bcafe6-fa7c-4697-b4ba-a1060bf968fc.png)
Which means that from select query a get Id as a string, when on practice it returns number
![image](https://user-images.githubusercontent.com/12869457/192156986-9958e37a-fc2e-4fc2-8474-72ee5024df20.png)
Am I missing something? (I'm using postgres dialect)

**Comment by RobinBlomberg** [comment]
This is very mysterious. The same Postgres data gives me the string `'1'`:

![Posg](https://user-images.githubusercontent.com/20827397/192162851-baeb0eaa-792d-4886-bffb-7ff939ab7bf3.png)

I updated to the newest `pg@^8.8.0` (and `kysely@^0.21.6`). Are you on an older version of `pg`?

**Comment by AlexandrLi** [comment]
This is my setup. I'm using sst framework, which internally generates types via kysely-codegen.
*package-lock.json*
![image](https://user-images.githubusercontent.com/12869457/192256683-8fb4349e-8741-4385-b1a2-a07b5a1de8c3.png)
*kysely*
![image](https://user-images.githubusercontent.com/12869457/192256852-885783bc-9e63-4985-a346-9f69ff660249.png)
*DB config*
![image](https://user-images.githubusercontent.com/12869457/192256903-6a9756b3-f4b4-4385-b21e-ccc294edf3ff.png)

**Comment by AlexandrLi** [comment]
@RobinBlomberg do you need anything else from my side for investigation? I would love to provide any information to help resolve this issue, just let me know. Thanks

**Comment by RobinBlomberg** [comment]
@AlexandrLi I did find this thread:

https://github.com/brianc/node-postgres/issues/1450

According to it, a `bigserial` *should* return a string, but it's possible that SST or RDS overrides the type with something like this:

```ts
types.setTypeParser(types.builtins.INT8, parseFloat);
```

References showing that `pg` returns a string for `bigserial` types by default:
https://github.com/charmander/pg-int8/blob/master/index.js#L23
https://github.com/brianc/node-pg-types/blob/master/lib/binaryParsers.js#L63
https://github.com/brianc/node-pg-types/blob/master/lib/textParsers.js#L71

So I will close this as "won't fix", but people have requested being able to override/customize types, so I will redirect to this issue: https://github.com/RobinBlomberg/kysely-codegen/issues/30.

**Comment by AlexandrLi** [comment]
Actually I found where custom parsing is happening https://github.com/serverless-stack/kysely-data-api/blob/master/src/data-api-query-compiler.ts. Maybe I will address this thread to the kysely-data-api package.
