### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by jschumacher-dexcom** [RobinBlomberg/kysely-codegen#33]
Hi @RobinBlomberg -- thanks for the great tool, it worked flawlessly for me.  Do you mind adding a LICENSE file?  Our workflow has an automated check that every library we use has a permissive license, and `kysely-codegen` got flagged as having no license.

Thank you!

**Comment by RobinBlomberg** [comment]
Good call! I will add this in the next release.

**Comment by RobinBlomberg** [comment]
Added in `kysely-codegen@0.7.1`!
