### ISSUE TITLE
Timestamp `SelectType` includes `RawBuilder`

### ISSUE THREAD

**Issue by jschumacher-dexcom** [RobinBlomberg/kysely-codegen#37]
When generating types for databases with timestamp fields (using Postgres adapter) the following type is used:

`export type Timestamp = ColumnType<Date | RawBuilder, Date | string | RawBuilder, Date | string | RawBuilder>;`

Having `RawBuilder` in the `SelectType` makes it harder to use data retrieved from the DB, as additional type-guard checks are needed.  Was it intended that `RawBuilder` be only part of the Insert/Update types?

**Comment by jschumacher-dexcom** [comment]
FYI-- I'm using the following work-around for now:

`export type ColumnWithoutSelectableRawBuilder<T> = T extends ColumnType<
  infer S,
  infer I,
  infer U
>
  ? ColumnType<Exclude<S, RawBuilder>, I, U>
  : T;

export type TableWithoutSelectableRawBuilders<T> = {
  [k in keyof T]: ColumnWithoutSelectableRawBuilder<T[k]>;
};

export type DatabaseWithoutSelectableRawBuilders<T> = {
  [k in keyof T]: TableWithoutSelectableRawBuilders<T[k]>;
};
`

**Comment by RobinBlomberg** [comment]
It should indeed only have been part of the insert/update types... I'll fix.

**Comment by RobinBlomberg** [comment]
Fixed in `kysely-codegen@0.7.1`!
