### ISSUE TITLE
Make kysely a peerDependency

### ISSUE THREAD

**Issue by koskimas** [RobinBlomberg/kysely-codegen#4]
Hi!

It would be better if Kysely was a required peer dep. Otherwise people can easily get two different versions of Kysely if the versions don't match.

Offtopic: This project is something a lot of people are asking for! Thank you for writing it! Please let me know what you need from Kysely and I'd be happy to make the changes/additions.

**Comment by RobinBlomberg** [comment]
Thank you! Published in 0.3.0. 🚀
