### ISSUE TITLE
Incorrect default path for generated types

### ISSUE THREAD

**Issue by 68kHeart** [RobinBlomberg/kysely-codegen#40]
# Description

When using the default out file path for the `db.d.ts` file, another `node_modules` folder is created within the module's folder.

# Expected Behavior

`kysely-codegen` creates the type definitions file at `<project root>/node_modules/kysely-codegen/dist/db.d.ts`

# Actual Behavior

`kysely-codegen` instead creates the type definitions file at `<project root>/node_modules/kysely-codegen/node_modules/kysely-codegen/dist/db.d.ts`

# Additional Details

This appears to be a regression introduced in b749a677e6bfd7370559767e57e4c69746898f94 when the constants were moved to a separate file. `__dirname` resolves to `<module root>/dist/constants` in the new file.

**Comment by RobinBlomberg** [comment]
Fixed in `kysely-codegen@0.7.3`!
