### ISSUE TITLE
Specifying schema for DB connection

### ISSUE THREAD

**Issue by w00ing** [RobinBlomberg/kysely-codegen#45]
Our project has several schemas in a single postgres database. Is there an option to target only specific schema? I already tried to set schema in database url like below,

`DATABASE_URL=postgres://username:password@yourdomain.com/database?schema=my_schema`
and
`DATABASE_URL=postgres://username:password@yourdomain.com/database?search_path=my_schema`

but neither worked. Is there any idea?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/45">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/45/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/45/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
It should be doable with `--include-pattern=my_schema.*`. That option appears to be broken at the moment, but it should be fixed for the next release.

**Comment by RobinBlomberg** [comment]
Try it out in `kysely-codegen@0.8.0`!

**Comment by eGust** [comment]
Just tried with `kysely-codegen@0.9.0` and didn't work.

Created a schema named `demo` and created table `test_foo` in both `public` and `demo`

```sql
CREATE TABLE demo.test_foo (
	id bigserial NOT NULL,
	"name" varchar(64) NULL,
	is_enabled bool NOT NULL DEFAULT true,
	CONSTRAINT test_foo_pk PRIMARY KEY (id)
);
```

Generated **without** `--include-pattern`:
```ts
export interface DemoTestFoo {
  id: Generated<Int8>;
  name: string | null;
  isEnabled: Generated<Boolean>;
}

export interface TestFoo {
  id: Generated<Int8>;
  name: string | null;
  isEnabled: Generated<Boolean>;
}

export interface DB {
  "demo.testFoo": DemoTestFoo;
  testFoo: TestFoo;
}
```

Generated **with** `--include-pattern 'demo.*'`:
```ts
export interface DemoTestFoo {
  id: Generated<Int8>;
  name: string | null;
  isEnabled: Generated<Boolean>;
}

export interface DB {
  "demo.testFoo": DemoTestFoo;
}
```

In my use case, there will be multiple schemas with the same structure. I don't want the `Demo` or `demo.` prefixes at all.

**Comment by maslennikov** [comment]
Right now filtering by schema and removing schema prefixes is possible due to https://github.com/RobinBlomberg/kysely-codegen/pull/56 like that:
```js
kysely-codegen --schema auth --include-pattern 'auth.*' 
```

But passing schema name like this is a bit awkward and inconsistent with `.env` file config when we define `DATABASE_URL`.

Maybe we could support another `.env` var to enable filtering with setting of something like `DATABASE_SCHEMA=auth`?

**Comment by RobinBlomberg** [comment]
I would say that this issue has been fixed with `--schema`, but I welcome anyone to create a new issue for supporting an env-based schema.
