### ISSUE TITLE
Use `import type` in the generated files

### ISSUE THREAD

**Issue by ooflorent** [RobinBlomberg/kysely-codegen#47]
The generated schema uses `import` to reference dependencies. For example:
```ts
import { ColumnType, RawBuilder } from "kysely";
import { IPostgresInterval } from "postgres-interval";
```

When compiled by `tsc`, the `import` statements are not removed:
```js
require("kysely");
require("postgres-interval");
```

However, when using `import type` (or `.d.ts` extension), the imports are correctly omitted.

**Comment by RobinBlomberg** [comment]
Oh wow. Good call! I will look into this.

**Comment by RobinBlomberg** [comment]
Added in `kysely-codegen@0.9.0`!
