### ISSUE TITLE
Introspect views

### ISSUE THREAD

**Issue by diogob** [RobinBlomberg/kysely-codegen#53]
Would there be interest in merging support for database view introspection?

There could be a CLI option to add views to the generated types so everything would be backwards compatible.

**Comment by MoSheikh** [comment]
Just came in to see if this was already requested 😅. Huge fan of this tool - would love to see this functionality in place to simplify logic.

**Comment by RobinBlomberg** [comment]
This sounds interesting! I don't personally use views that much, but if this is a requested feature, I'm all for it.

**Comment by diogob** [comment]
The `getTables` in hte kysely introspector now will return views metadata, so most (if not all) functionality will be ready once the next version is released. I'll check if any further changes will be needed on the kysely-codegen side.
