### ISSUE TITLE
Postgres better support for custom domains

### ISSUE THREAD

**Issue by andrew-w-ross** [RobinBlomberg/kysely-codegen#55]
When using a custom domain the generated value always seems to be string even though the underlying shouldn't be.

## The Problem

Given the following schema:

```sql
CREATE domain "public"."pos_int" AS Integer CONSTRAINT positive_number CHECK (value >= 0);

CREATE TABLE foo (value pos_int NOT NULL DEFAULT 0);
```  

The generated type will be:

```ts
export interface Foo {
  value: Generated<string>;
}
```

I assumed maybe this was by design maybe `pg` returns the value as string so I wrote a test to confirm:

```ts
//Db argument is Kysely<DB> instance 
it('value is a number', async ({db}) => {
    //@ts-expect-error value is actually a number 
    const result = await db.insertInto('foo').values({
        value: 12
    }).returningAll().executeTakeFirstOrThrow();

    expect(result).toMatchObject({
        value: 12
    });

    expect(result).not.toMatchObject({
        value: "12"
    });
});
```

Turns out that the `pg` does respect the base type of the domain when materializing so the type is wrong.

## What's expected 

That the type generated is of type number:

```ts
export interface Foo {
  value: Generated<number>;
}
```

## Proposed solution

I'm happy to write a pr to fix this but I just wanted to raise this issue and see if you agree with my solution before starting.
I was thinking of modifying the [postgres introspector and getting the underlying datatype](https://github.com/RobinBlomberg/kysely-codegen/blob/master/src/dialects/postgres/postgres-introspector.ts#L23).
I haven't looked too far into it but I think I'll have to add an `#introspectDomains` function to get the base type.

Let me know what you think.

**Comment by RobinBlomberg** [comment]
Interesting! I haven't given domains any thought, but this seems to be a real bug. I haven't investigated, but I was wondering whether this should be changed in kysely or kysely-codegen.

I guess if kysely correctly returns the type `pos_int`, it is indeed up to us to implement `#introspectDomains`, so feel free to go ahead! 👏
