### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by RobinBlomberg** [RobinBlomberg/kysely-codegen#6]
I plan to add MySQL support to give the package feature parity with Kysely.

**Comment by igalklebanov** [comment]
Looking forward to it!

**Comment by DavesBorges** [comment]
#8

**Comment by RobinBlomberg** [comment]
I'm implementing MySQL support in #12. It should be noted that it uses this connection string format (which `mysql2` appears to understand):
```
mysql://user:password@localhost/database
```

If [Connector/NET](https://dev.mysql.com/doc/connector-net/en/connector-net-connections-string.html)-style connection strings are deemed desirable, it may be implemented in the future. But it may be a separate issue in that case.
