### ISSUE TITLE
Error with mysql2@3.1.2

### ISSUE THREAD

**Issue by bcerquiare** [RobinBlomberg/kysely-codegen#62]
I'm attempting to install a library, but I encountered an error related to the mysql2 version, which stated that the library only works with version 2.3.3. At present, mysql2 is on version 3.1.2.

**Comment by RobinBlomberg** [comment]
What's the error you encounter?

**Comment by nlindroos** [comment]
Currently `"mysql2": "^2.3.3"` is defined as a peer dependency. At least with npm@9.5.0 installing a 3.x version of `mysql2` results in an `ERESOLVE could not resolve` error.

**Comment by RobinBlomberg** [comment]
Should be fixed in `kysely-codegen@0.10.1`!
