### ISSUE TITLE
` DATABASE_URL` should alias `pg://` to `postgres://`

### ISSUE THREAD

**Issue by loynoir** [RobinBlomberg/kysely-codegen#67]
### Actual
```sh
$ DATABASE_URL="pg://xxx" npm exec kysely-codegen
• Loaded environment variables from .env file.
• No dialect specified. Assuming 'sqlite'.
node:internal/modules/cjs/loader:1075
  const err = new Error(message);
              ^

Error: Cannot find module 'better-sqlite3'
Require stack:
```

### Expected
```sh
$ DATABASE_URL="postgres://xxx" npm exec kysely-codegen
• Loaded environment variables from .env file.
• No dialect specified. Assuming 'postgres'.
• Introspecting database...
✓ Introspected 10 tables and generated ./node_modules/kysely-codegen/dist/db.d.ts in 20ms.
```

### Version
```sh
$ grep version node_modules/kysely-codegen/package.json
  "version": "0.10.0",
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/67">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/67/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/67/pledge.svg">
</picture>
</a>

**Comment by akxcv** [comment]
Also `postgresql://` is a valid protocol for postgres

**Comment by flyingherdi** [comment]
Have the same error with v. 0.10.0: 

`npm exec kysely-codegen
• Loaded environment variables from .env file.
• No dialect specified. Assuming 'sqlite'.
node:internal/modules/cjs/loader:1048
  const err = new Error(message);
              ^

Error: Cannot find module 'better-sqlite3'
Require stack:
- /Users/janschroder/Documents/GitHub/LinguaCloud/backend/node_modules/kysely-codegen/dist/dialects/sqlite/sqlite-dialect.js
- /Users/janschroder/Documents/GitHub/LinguaCloud/backend/node_modules/kysely-codegen/dist/dialects/sqlite/index.js
- /Users/janschroder/Documents/GitHub/LinguaCloud/backend/node_modules/kysely-codegen/dist/dialects/index.js
- /Users/janschroder/Documents/GitHub/LinguaCloud/backend/node_modules/kysely-codegen/dist/dialect-manager.js
- /Users/janschroder/Documents/GitHub/LinguaCloud/backend/node_modules/kysely-codegen/dist/cli.js
- /Users/janschroder/Documents/GitHub/LinguaCloud/backend/node_modules/kysely-codegen/dist/bin/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at /Users/janschroder/Documents/GitHub/LinguaCloud/backend/node_modules/kysely-codegen/dist/dialects/sqlite/sqlite-dialect.js:38:87
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SqliteDialect.createKyselyDialect (/Users/janschroder/Documents/GitHub/LinguaCloud/backend/node_modules/kysely-codegen/dist/dialects/sqlite/sqlite-dialect.js:38:39)
    at async SqliteIntrospector.connect (/Users/janschroder/Documents/GitHub/LinguaCloud/backend/node_modules/kysely-codegen/dist/introspector.js:18:33)
    at async Cli._Cli_generate (/Users/janschroder/Documents/GitHub/LinguaCloud/backend/node_modules/kysely-codegen/dist/cli.js:120:16)
    at async Cli.run (/Users/janschroder/Documents/GitHub/LinguaCloud/backend/node_modules/kysely-codegen/dist/cli.js:94:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/janschroder/Documents/GitHub/LinguaCloud/backend/node_modules/kysely-codegen/dist/dialects/sqlite/sqlite-dialect.js',
    '/Users/janschroder/Documents/GitHub/LinguaCloud/backend/node_modules/kysely-codegen/dist/dialects/sqlite/index.js',
    '/Users/janschroder/Documents/GitHub/LinguaCloud/backend/node_modules/kysely-codegen/dist/dialects/index.js',
    '/Users/janschroder/Documents/GitHub/LinguaCloud/backend/node_modules/kysely-codegen/dist/dialect-manager.js',
    '/Users/janschroder/Documents/GitHub/LinguaCloud/backend/node_modules/kysely-codegen/dist/cli.js',
    '/Users/janschroder/Documents/GitHub/LinguaCloud/backend/node_modules/kysely-codegen/dist/bin/index.js'
  ]
}`

Trying with ` DATABASE_URL="pg://xxx" `.

**Comment by flyingherdi** [comment]
Have the same error with v. 0.10.0: 

```
npm exec kysely-codegen
• Loaded environment variables from .env file.
• No dialect specified. Assuming 'sqlite'.
node:internal/modules/cjs/loader:1048
  const err = new Error(message);
              ^

Error: Cannot find module 'better-sqlite3'
```


Trying with ` DATABASE_URL="pg://xxx" `.

**Comment by AdamZaczek** [comment]
Bump. I'm excited about the premise of the tooling but inability to connect easily made me procrastinate on trying the tool further. The reasoning is - if this common scenario crashes, more problems are likely coming.

**Comment by RobinBlomberg** [comment]
I believe I have fixed this, but I missed closing this issue.

[This file](https://github.com/RobinBlomberg/kysely-codegen/blob/master/src/core/connection-string-parser.test.ts) asserts that `postgres://`, `postgresql://` and `pg://` all work.

Also, I would like to remind everyone that this is an open source project I work on for free, and pull requests are warmly welcome. But this issue should be resolved now.
