### ISSUE TITLE
add support for camelCase

### ISSUE THREAD

**Issue by seeden** [RobinBlomberg/kysely-codegen#7]
Hi,

Please, can you add support for camelCase?
I am using CamelCasePlugin with kysely and types are not correct.

Thank you for this great package

**Comment by RobinBlomberg** [comment]
Great idea! I will try to implement this in 0.4.1 soon.

**Comment by seeden** [comment]
Thank you

**Comment by RobinBlomberg** [comment]
Implemented in 0.5.0!

**Comment by seeden** [comment]
Thank you :)

**Comment by daniel-gato** [comment]
Is this out of the box or do we need to do something to enable it?

**Comment by shane-js** [comment]
Just found this issue when searching as I need it too. I read through the linked commit from 0.5.0 to see you simply pass "--camel-case" arg when you run  'kysely-codegen' (i.e. 'kysely-codegen --camel-case'). 

I am going to put up a PR to start a section in the doc to expose some of these args that you wouldn't know about unless you went looking for them.
