### ISSUE TITLE
Define types for JSON columns

### ISSUE THREAD

**Issue by daffron** [RobinBlomberg/kysely-codegen#75]
Hey!, First thanks for creating this tool - saves time for sure!

This is probably similar to https://github.com/RobinBlomberg/kysely-codegen/issues/30

However that seemed focused on deriving the types from ENUMs and headed down a different path.

I was wondering if theres any way to achieve the following:

```
export interface IMarkertingData {
 someValue: string;
}
```

```
export interface User {
  created_at: Generated<Timestamp | null>;
  email: string;
  first_name: string | null;
  id: Generated<string>;
  last_name: string | null;
  marketing_data: IMarkertingData | null;
  updated_at: Generated<Timestamp | null>;
}
```

Currently I had to use the codegen as a once off, save the file in my source code and modify / keep updated manually. Which I assume isnt the intended use?

Thanks!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/75">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/75/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/75/pledge.svg">
</picture>
</a>

**Comment by maccman** [comment]
Same question :)

**Comment by igalklebanov** [comment]
Hey 👋 

If this is possible, it could be very helpful for type-safe JSON traversal https://github.com/kysely-org/kysely/pull/440 that was released in kysely v0.26.

**Comment by RobinClowers** [comment]
@koskimas suggested that json types should be any or unknown. Currently the Json type that is generated requires us to drop down to sql template string to actually do anything useful with a json column.

**Comment by jjdonov** [comment]
From the outside looking in, I'd think that would be really hard to generate. Any json/b column could have completely different contents.

I wonder if this becomes a simpler problem if something like https://github.com/supabase/pg_jsonschema were used to constrain the column

**Comment by noppa** [comment]
One way to do this could be to generate another file for the json column - if one doesn't exist already - and not automatically modify it after that, so it'd be safe to edit it to contain the column type.

For example, it could generate something like 

```typescript
// jsonb-MarketingData.d.ts
export type MarketingData = unknown

// database.d.ts
import type {MarketingData} from './jsonb-MarketingData'

export interface User {
  marketing_data: MarkertingData | null;
}
```
Then the developer would be free to modify that `unknown` type to something else, without fearing that it will be overridden later.

**Comment by bombillazo** [comment]
I agree this is needed to extend or override types with developer known types. @noppa 's idea would be great since you isolate manual types from auto-generated types.

**Comment by mb21** [comment]
Plus one. Came here from https://kysely.dev/docs/recipes/extending-kysely where they access the `address` JSON field by declaring the type:

```ts
interface DB {
  person: {
    address: {
      postalCode: string
      street: string
    }
  }
}
```

But if you're using `kysely-codegen` this seems to be currently impossible to do? Unless you post-process the generated file with a manual string search-and-replace with `sed` or similar...

**Comment by Exellin** [comment]
I ended up solving this with a script locally by adding the type to a comment in the database through a migration file, using the functionality in Kanel as an inspiration: https://github.com/kristiandupont/kanel/issues/429.

```ts
`await sql`COMMENT ON COLUMN habits.amount_thresholds_by_frequency IS '@type:{ [key: number]: {min: number, max: number} }'`.execute(db);`
```

Then I create a script file to run right after a migration, grabbing everything after `@type` if it exists:

```ts
// based on https://github.com/RobinBlomberg/kysely-codegen/issues/90#issuecomment-1825032368

import db from '../';
import { readFileSync, writeFileSync } from 'fs';

const transformFile = async () => {
  const filePath = process.argv[2];

  if (!filePath) {
    console.error('No file path provided!');
    return;
  }

  const content = readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');
  let dbInterfaceLineIndex = lines.findIndex((line) => {
    return line === 'export interface DB {';
  });

  if (dbInterfaceLineIndex === -1) {
    console.warn("Couldn't find `export interface DB {`! This script is fragile and the result is probably wrong!");
    dbInterfaceLineIndex = Number.MAX_SAFE_INTEGER; // So that the check below doesn't return true;
  }

  const tables = await db.introspection.getTables();
  db.destroy();

  let tableName: string;

  const transformedLines = lines.flatMap((line) => {
    if (line.includes('export interface')) {
      tableName = line.split('export interface')[1].split('{')[0].trim().toLowerCase();
    }
    if (line.includes(': Json;')) {
      const columnName = line.split(': Json')[0].trim();
      if (tableName && columnName) {
        const table = tables.find((table) => table.name == tableName);
        const column = table?.columns.find((column) => column.name == columnName);
        const type = column?.comment?.split('@type:')[1];

        if (type) return line.replace('Json', type);
      }

      return line;
    }

    return line;
  });

  writeFileSync(filePath, transformedLines.join('\n'), 'utf-8');
};

transformFile();
```

and added these scripts to my `package.json`:

```json
    "replace-json": "ts-node db/scripts/insertJsonTypes db/schema.d.ts",
    "migrate": "ts-node db/scripts/migrateToLatest && kysely-codegen --out-file db/schema.d.ts && npm run replace-json"
 ```
 
 If there is interest I could work on a PR to implement this functionality into kysely-codegen.

**Comment by probablykabari** [comment]
Coming here from working on another typescript postgres library. The way that library handles this is the type for JSON columns is generated separately as a default value that you can update in a non-generated file, similar to what @noppa has suggested. That is very flexible and convenient.

**Comment by sfratini** [comment]
I am currently doing this:

```
import {DB, Question} from './db.types'
import {QuestionScoreConfig, QuestionType, QuestionValidation} from "../types/graphql";

interface EnhancedQuestionType extends Omit<Question, 'options' | 'score' | 'type' | 'validation'> {
    options: string[],
    score: QuestionScoreConfig,
    type: QuestionType,
    validation: QuestionValidation
}

export interface EnhancedDB extends Omit<DB, 'question'> {
    question: EnhancedQuestionType
}
```

First import is the results from kysely-codegen. Second import is the auto generated types from graphql-codegen. I am just overriding the types for the JSON columns. The JSON types are generated directly into Graphql schema but it would not matter . QuestionType is an enum so it also works for inserts:


```
    const singleSelect = await kysely.updateTable('question')
        .where('type', 'is', null).where('idDdQuestionType', '=', 1)
        .set('type', QuestionType.SingleSelect)
        .executeTakeFirst();

```

Then I just do Kysely<EnhancedDB> and that is it.

**Comment by RobinBlomberg** [comment]
Should be released in [kysely-codegen@0.16.0](https://github.com/RobinBlomberg/kysely-codegen/releases/tag/0.16.0)! 🚀

**Comment by bombillazo** [comment]
Hey, just saw this, is there any documentation on how this new feature works? 

We have a post-processing script that updates all our imports and wanted to see if now we can do it directly with this codegen

**Comment by RobinClowers** [comment]
@bombillazo Looks like this comment describes it: https://github.com/RobinBlomberg/kysely-codegen/pull/148#issuecomment-2047907063, but it would be awesome to include an example in the readme.

**Comment by mb21** [comment]
That's awesome! Has anybody got a working example of a JSON column with imports and all? I cannot seem to find where to import `GenericExpressionNode` or `JSONColumnType` from.

**Comment by stoicskyline** [comment]
Here's a example implementation, not sure if it's what's recommended, but I think it's clean enough:

```js
import { CustomAddress } from './custom-types.ts'
import { ColumnType } from 'kysely'
import * as GeneratedTypes from './kysely-types.gen'

export interface SggCharacters extends Omit<
  GeneratedTypes.Authors,
  'mailAddress'
  | 'billAddress'
> {
  mailAddress: ColumnType<CustomAddress>
  billAddress: ColumnType<CustomAddress>
}

export interface DB extends Omit<
  GeneratedTypes.DB,
  'authors'
> {
  authors: Authors
}
```

For reference, we can do this because this package declares:
```
export type JSONColumnType<SelectType extends object | null, InsertType = string, UpdateType = string> = ColumnType<SelectType, InsertType, UpdateType>;

export type ColumnType<SelectType, InsertType = SelectType, UpdateType = SelectType> = {
```

So you can use whichever type suits your particular use case, i.e. if you want the inserts to be your custom type, then use `ColumnType`

cc @bombillazo @mb21

**Comment by crisanmm** [comment]
I've been trying to figure out how to better type a JSON column as well and I've had trouble understanding the `--overrides` argument over in the README file 😅, turns out it was easier to use than I thought. Below I'll share my context and what I did to type a JSON column.

Without passing any `overrides` option to `kysely-codegen`, for this postgresql table:
```sql
create table public.tests (
  id uuid not null default gen_random_uuid(),
  created_at timestamp with time zone not null default now(),
  questions jsonb not null
);
```
it outputs the following generated types in a file named `generated-db-types.ts`:
```ts
export interface Test {
  id: Generated<string>;
  created_at: Generated<Timestamp>;
  questions: Json;
}
```
Even though `questions` is of type JSON in my use case it'll still follow a structure, however the generated `Json` type is way too broad for my case. In my case, I want to type the `questions` column like this:
```ts
type TestQuestionType = {
  id: string;
  question: string;
  answer: string;
};
```
I've edited my `.kysely-codegenrc.ts` file to add the `overrides` option (for brevity purposes I removed the other options I have in my config file):
```ts
import { type Config } from 'kysely-codegen';

export default {
  overrides: {
    columns: {
      'tests.questions': `{
        id: string;
        question: string;
        answer: string;
      }[]`,
      /**
       * alternatively, you can also type it like below,
       * however I don't know about the pros/cons of this approach
       */
      // 'tests.questions': new ArrayExpressionNode(
      //   new ObjectExpressionNode([
      //     new PropertyNode('id', new RawExpressionNode('string')),
      //     new PropertyNode('question', new RawExpressionNode('string')),
      //     new PropertyNode('answer', new RawExpressionNode('string')),
      //   ])
      // ),
    },
  },
} satisfies Config;
```
and now when I re-generate the types, this is what is outputted in the generated types file `generated-db-types.ts` 🎉: 
```ts
export interface Test {
  id: Generated<string>;
  created_at: Generated<Timestamp>;
  questions: {
    id: string;
    question: string;
    answer: string;
  }[];
}
```
