### ISSUE TITLE
Codegen does not typecheck implicitly and importing Type fails overload

### ISSUE THREAD

**Issue by pthieu** [RobinBlomberg/kysely-codegen#77]
Testing out the library and running into type-checking issues, not sure if I have things set up properly.

I have this migration:

```js
import { Kysely, sql } from 'kysely';

const TABLE_NAME = 'users';

export async function up(db: Kysely<any>): Promise<void> {
  await db.schema
    .createTable(TABLE_NAME)
    .addColumn('id', 'uuid', (col) =>
      col.primaryKey().defaultTo(sql`uuid_generate_v4()`),
    )
    .addColumn('email', 'text', (col) => col.unique().notNull())
    .addColumn('created_at', 'timestamptz', (col) => col.defaultTo(sql`now()`))
    .execute();
}

export async function down(db: Kysely<any>): Promise<void> {
  await db.schema.dropTable(TABLE_NAME).execute();
}
```

I can then do this:

```js
  const user = {
    email: 'test@gmail.com',
    shouldNotWork: 'test',
  };
  await db.insertInto('users').values(user).returningAll().execute();
```

But I will not get an error in VSCode:
![image](https://github.com/RobinBlomberg/kysely-codegen/assets/2908721/fd48bc62-3af3-440e-a4a6-53e064a7372f)

If I run this code, it will not work as expected:
![image](https://github.com/RobinBlomberg/kysely-codegen/assets/2908721/8de1629b-d9c8-44ea-b7d4-ccd0f5f83490)

If I import the type directly from the generated file:
```js
  import { Users } from 'kysely-codegen';
  ...
  const user: Users = {
    email: 'test@gmail.com',
    shouldNotWork: 'test',
  };
  await db.insertInto('users').values(user).returningAll().execute();
```

I'll get the correct type check error:
![image](https://github.com/RobinBlomberg/kysely-codegen/assets/2908721/d2d842e8-34d7-4ad7-88e1-f1961d5d9ea7)

However I now get this overload error:
![image](https://github.com/RobinBlomberg/kysely-codegen/assets/2908721/6e5e8661-fcf7-4b5a-a542-9c2f68eb0840)

**Comment by pthieu** [comment]
Update, so the 2nd issue is an error on my part, I needed to make the user Insertable:

```
const user: Insertable<User> = {
    email: 'test@example.com',
  };
```

**Comment by RobinBlomberg** [comment]
Glad you solved it! 👍

It is an unfortunate limitation of TypeScript that you can pass around objects with extra properties without error, unless you type the object during instantiation. Your solution is the way to go.
