### ISSUE TITLE
Special characters in password: It's not an issue

### ISSUE THREAD

**Issue by ram-you** [RobinBlomberg/kysely-codegen#78]
If the username or password includes the following characters:
: / ? # [ ] @
those characters must be converted using :
[percent encoding.](https://tools.ietf.org/html/rfc3986#section-2.1) 

and change database connection string to this:
DATABASE_URL=mysql://yourdomain.com/database?user=root&password=_**URL encoded password**_

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/RobinBlomberg) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/RobinBlomberg/kysely-codegen/issues/78">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/78/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/RobinBlomberg/kysely-codegen/issues/78/pledge.svg">
</picture>
</a>

**Comment by RobinBlomberg** [comment]
Can you explain a bit more what the issue is?

Which statement (if any) is correct?
1. The user cannot use codegen at all if their password has those characters, and there's no workaround
2. The user can use codegen if they manually encode their password, and the documentation should reflect that
3. The user can use codegen if they manually encode their password, but the codegen should do it for them

**Comment by ram-you** [comment]
Thank you for your response. 
The correct statement would be:
The user can use codegen if they manually encode their password, and the documentation should reflect that.
By manually encoding the password using percent encoding (URL encoding), the user can include special characters such as :, /, ?, #, [, ], and @ in their MySQL connection string.

It's important to note that the codegen functionality itself does not automatically encode the password. Users need to manually perform the encoding and update the connection string accordingly.

Please let me know if you have any further questions or need more information. 
Thank you.

**Comment by RobinBlomberg** [comment]
Thanks for the clarification! The documentation is in need of a general upgrade, and this seems like a reasonable addition.
