### ISSUE TITLE
This is not a bug report, this is a thank you

### ISSUE THREAD

**Issue by paco-sparta** [RobinBlomberg/kysely-codegen#80]
Y'all just saved us hours and hours of toil & pain. Have a happy duck!

![https://media.tenor.com/3YeFSzC3p5gAAAAC/happy-duck.gif](https://media.tenor.com/3YeFSzC3p5gAAAAC/happy-duck.gif)

**Comment by RobinBlomberg** [comment]
This made me happy to see! 🥰 Thank you, and glad you like it!
