### ISSUE TITLE
unable to use mysql@3* as peer dependency

### ISSUE THREAD

**Issue by elitan** [RobinBlomberg/kysely-codegen#82]
This [PR](https://github.com/RobinBlomberg/kysely-codegen/pull/69) seems to be using an incorrect syntax for adding support for multiple major versions of `mysql2`.

Correct syntax:

```
    "mysql2": "^2.3.3 || ^3.0.0",
```

For now I can get around this issue by using `npm install --save-dev kysely-codegen --force`.

**Comment by elitan** [comment]
cc @devunt

**Comment by RobinBlomberg** [comment]
Should be fixed in `kysely-codegen@0.10.1`!
