### ISSUE TITLE
unable to run kysely-codegen

### ISSUE THREAD

**Issue by marcotglb** [RobinBlomberg/kysely-codegen#84]
Sorry for this question that could be trivial for most of you.

I'm just unable to run the "kysely-codegen" command.

I created an empty forlder and jumped in.
$ npm init 
$ npm install --save-dev kysely-codegen
$ npm install kysely pg

Then I created my .env file.

but no 'kysely-codegen' is there

I tried to run 'node ./node_modules/.bin/kysely-codegen'  but I'm getting this output.

/opt/prjs/deno_prjmgmt/kysley-codegen/node_modules/kysely/dist/cjs/kysely.js:79
            const log = new log_js_1.Log(args.log ?? []);
                                                   ^
SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/prjs/deno_prjmgmt/kysley-codegen/node_modules/kysely/dist/cjs/index.js:18:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

thaks for you help

**Comment by igalklebanov** [comment]
Hey 👋 

Can you `node -v` in your terminal to check what Node.js version you're trying to run this on?

It fails on nullish coalescing, supported in Node.js since v14.

![image](https://github.com/RobinBlomberg/kysely-codegen/assets/14938291/65244c20-6966-4fd7-8663-2cb66c3490c8)

**Comment by shakibhasan09** [comment]
@marcotglb  you can try with "npx kysely-codegen "

**Comment by RobinBlomberg** [comment]
This indeed sounds like you're using an old Node version. Try upgrading to the [LTS version of Node.js](https://nodejs.org/en). If that doesn't work, I'll reopen this issue.

**Comment by stlbucket** [comment]
I am seeing similar issues

<img width="1146" alt="image" src="https://github.com/RobinBlomberg/kysely-codegen/assets/2467892/fb59219c-1d44-4128-86b3-61e4185cdcbd">

my package.json
```
{
  "name": "db-types",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "kysely-codegen": "^0.10.1"
  },
  "dependencies": {
    "kysely": "^0.26.1",
    "pg": "^8.11.3"
  }
}
```

**Comment by stlbucket** [comment]
I am experiencing the same issue with node 18.17.0.

```
╰─➤  kysely-codegen                                                                                                                                              1 ↵
zsh: command not found: kysely-codegen
```

If I run npx kysely-codegen, I get this error:

```
╰─➤  npx kysely-codegen                                                                                                                                        127 ↵
• Loaded environment variables from .env file.
• No dialect specified. Assuming 'sqlite'.
node:internal/modules/cjs/loader:1077
  const err = new Error(message);
              ^

Error: Cannot find module 'better-sqlite3'
```

my package.json
```
{
  "name": "db-types",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "kysely-codegen": "^0.10.1"
  },
  "dependencies": {
    "kysely": "^0.26.1",
    "pg": "^8.11.3"
  }
}
```

**Comment by marcotglb** [comment]
Thanks for your suggestions.
Using Node 18 and npx it is now working.
