### ISSUE TITLE
"Generated" is created in output, but Kysely has this type

### ISSUE THREAD

**Issue by matthiasfeist** [RobinBlomberg/kysely-codegen#88]
I noticed that when I run the codegen, I get the following lines in my output file:
```typescript
export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;
```

However, Kysely already exports a "Generated" type via `import type { Generated } from 'kysely';`, so I was wondering why codegen is creating its own type?

**Comment by RobinBlomberg** [comment]
Oh right! I knew I added my own `Generated` implementation for a reason.

Some types already use `ColumnType`:
```ts
export type Json = ColumnType<JsonValue, string, string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;
```
So this special type is necessary in order to do this:
```ts
export interface User {
  created_at: Generated<Timestamp>;
//            ^ ColumnType<Date, Date | string | undefined, Date | string>
}
```
Otherwise the type would be equal to this monstrosity:
```ts
export interface User {
  created_at: Generated<Timestamp>;
//            ^ ColumnType<
//                ColumnType<Date, Date | string, Date | string>,
//                ColumnType<Date, Date | string, Date | string> | undefined,
//                ColumnType<Date, Date | string, Date | string>
//              >
}
```

**Comment by shane-js** [comment]
I just ran into this issue as I had removed it thinking it was in conflict/redundant to kysely's Generated type. Any appetite for renaming the Generated type codegen spits out to maybe something that describes the intent / difference?
