### ISSUE TITLE
Generation was "successful" but type file is empty

### ISSUE THREAD

**Issue by deanc** [RobinBlomberg/kysely-codegen#91]
Hi,

We have quite a large database, 100+ tables and some of those tables have 100+ fields (don't ask). I ran the codegen and it says it wrote the type file, but when I check it this is the contents:
```
export type DB = {};
```

I've ran in full debug mode, and also with --print - but basically there's no errors. It lists all the tables, so it's connecting okay but it's not generating the types. How should I proceed to debug?

**Comment by RobinBlomberg** [comment]
Hello! Thanks for reporting this. I will probably need some help troubleshooting this, as it works for me. The most basic way to troubleshoot would probably be to try to add some console.logs into the kysely-codegen code.

**Comment by deanc** [comment]
I can no longer reproduce this with the current release.

**Comment by RobinBlomberg** [comment]
Oh wow! I'm not what would've solved it in the latest release, but I'm happy to hear that! I guess I'll close this unless it pops up again.
